### PR TITLE
migrate @gemaxr's catalan and spanish translations to this repo

### PR DESCRIPTION
**Pull request by RogerTangos**
Hey @3nd64m3 , either the readme's out of date, or the addition of some markdown files has broken the build. When `make preview`, my local server is a `public` file directory.

... which is why I'm opening this as a PR instead of just pushing to master. Can you give it a look and make sure it's not breaking anything?

### CODE REVIEW

**Comment by 3nd64m3** [comment]
I fixed the site preview. It was still serving from `public` which we renamed to `docs`.

I also added the things-to-come path translations for es and cat.

Now what's left to do is to add the translated titles to the [YAML file](https://github.com/xr-comic-science/website/blob/cat-es/_src/data/things-to-come.yaml), e.g. (I used google to translate)

```diff
 - key: too-hot-to-live
   title:
     de: Zu heiß zum Leben!
     en: Too Hot To Live!
+    es: Demasiado caliente para vivir
+    cat: Massa calor per viure
```

**Comment by RogerTangos** [comment]
I added the headlines but am still having trouble with two issues.

- The overview text on both the catalan and spanish texts are in English, despite there being .md text. Is there an easy fix for this? http://localhost:5000/cat/coses-per-venir
- The spanish page continues to link to English versions. I poked at this for a bit, but don't understand what's happening there. http://localhost:5000/es/las-cosas-por-venir

**Comment by 3nd64m3** [comment]
Found another bug that was related to us migrating to Github (for which we had to rename the `public` folder to `docs`). This is fixed now. I also removed the project description from the non-English index pages and added an English sentence that links to the English page.

image

The only thing I see missing now are the descriptions for each of the things to come which are stored in the YAML header of each sub-page, e.g. https://github.com/xr-comic-science/website/blob/cat-es/_src/pages/es/las-cosas-por-venir/hot-war.md#L4

**Comment by 3nd64m3** [comment]
I'm merging this anyway since the website build is fixed and the translated descriptions (aka short versions of the texts) can be added in a future PR as well.

**Pull request merged**
